name: student_performance_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

  # CSV / Excel import dependencies
  file_picker: ^10.3.8
  csv: ^6.0.0
  excel: ^4.0.3
  path_provider: ^2.1.5

  # Printing and PDF generation
  printing: ^5.14.2
  pdf: ^3.11.3

  # Charts
  fl_chart: ^1.1.1

  # Web JS interop (optional)
  js: ^0.6.7

  # Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
